[package]
authors = ["AUTHOR_REPLACE"]
edition = "2021"
homepage = "https://traverseresearch.nl"
license = "LicenseRef-Traverse-Proprietary"
name = "app-template"
version = "0.1.0"

[workspace]

[features]
pre_cooked_assets = ["breda/pre_cooked_assets"]
