[package]
name = "{{ template_id }}"

[dependencies]
breda.workspace = true
breda-app-support.workspace = true
clap.workspace = true
anyhow.workspace = true

[build-dependencies]
breda-build.workspace = true
